### ISSUE TITLE
error al seleccionar querer seguir jugando o no 

### ISSUE THREAD

**Issue by EverRM** [alelolek/Trivia#1]
![image](https://user-images.githubusercontent.com/113306640/190809798-c2205cc7-566f-4b49-a41a-5598d273bb08.png)

**Comment by alelolek** [comment]
Al colocar cualquier otra palabra diferente a "Si", finaliza el programa, pero el interprete de Python sigue ejecutando sentencias, por lo tanto no es un error de código sino propio de replit. 

Gracias a tu feedback, se actualizó el mensaje final del programa para que sea más descriptivo.

![image](https://user-images.githubusercontent.com/58942657/190876286-75947bab-04c8-4bb8-8492-753c15e96668.png)
